dictionary:
  1:
    word: 'podzielony'
    translated_word: 'divided'
  2:
    word: 'rozsądny'
    translated_word: 'sane'
  3:
    word: 'dogonić'
    translated_word: 'catch up'
  4:
    word: 'rozsądny'
    translated_word: 'reasonable'
  5:
    word: 'nawyk'
    translated_word: 'habit'
  6:
    word: 'pilnie'
    translated_word: 'urgently'
  7:
    word: 'dbać'
    translated_word: 'take care'
  8:
    word: 'ciasno'
    translated_word: 'tightly'
  9:
    word: 'stowarzyszenie'
    translated_word: 'association'
  10:
    word: 'tendencja do narzekania'
    translated_word: 'tend to complain'
  11:
    word: 'spostrzeżenia'
    translated_word: 'insights'
  12:
    word: 'nie skleja się'
    translated_word: 'not sticking'
  13:
    word: 'tendencyjny'
    translated_word: 'preconceived'
  14:
    word: 'szczery'
    translated_word: 'honest'
  15:
    word: 'poufność'
    translated_word: 'confidentiality'
  16:
    word: 'za'
    translated_word: 'behind'
  17:
    word: 'spokojna'
    translated_word: 'calm'
  18:
    word: 'nagle'
    translated_word: 'suddenly'
  19:
    word: 'wyjaśnić'
    translated_word: 'explain'
  20:
    word: 'zmierzać'
    translated_word: 'tend'
  21:
    word: 'wydajnie'
    translated_word: 'efficiently'
  22:
    word: 'ostatnio'
    translated_word: 'lately'
  23:
    word: 'prawie'
    translated_word: 'almost'
  24:
    word: 'dostarczanie'
    translated_word: 'providing'
  25:
    word: 'dania na wynos'
    translated_word: 'takeaways'
  26:
    word: 'założyć'
    translated_word: 'assume'
  27:
    word: 'wyraźny'
    translated_word: 'explicit'
  28:
    word: 'wysiłek'
    translated_word: 'effort'
  29:
    word: 'oprogramowanie pośredniczące'
    translated_word: 'middleware'
  30:
    word: 'często'
    translated_word: 'often'
  31:
    word: 'żywy'
    translated_word: 'alive'
  32:
    word: 'przykuty'
    translated_word: 'chained'
  33:
    word: 'odwołać się'
    translated_word: 'invoke'
  34:
    word: 'umowa'
    translated_word: 'agreement'
  35:
    word: 'cele'
    translated_word: 'objectives'
  36:
    word: 'uruchomić'
    translated_word: 'launch'
  37:
    word: 'Rada'
    translated_word: 'advice'
  38:
    word: 'doradzać'
    translated_word: 'advise'
  39:
    word: 'prowadzi nas'
    translated_word: 'brings us'
  40:
    word: 'nieszczelność'
    translated_word: 'leak'
  41:
    word: 'cisza'
    translated_word: 'silence'
  42:
    word: 'w zasadzie ktoś'
    translated_word: 'someone basically'
  43:
    word: 'brak'
    translated_word: 'lack'
  44:
    word: 'nieprzerwany'
    translated_word: 'uninterrupted'
  45:
    word: 'jednostka'
    translated_word: 'unit'
  46:
    word: 'uprawniona'
    translated_word: 'entitled'
  47:
    word: 'także'
    translated_word: 'as well'
  48:
    word: 'jak podejść'
    translated_word: 'how to approach'
  49:
    word: 'cichy'
    translated_word: 'silent'
  50:
    word: 'dzięki za udział'
    translated_word: 'thanks for attending'
  51:
    word: 'brać udział w'
    translated_word: 'attend'
  52:
    word: 'obciążenie'
    translated_word: 'burden'
  53:
    word: 'blask'
    translated_word: 'shine'
  54:
    word: 'dowiedziałem się'
    translated_word: 'found out'
  55:
    word: 'całkowicie'
    translated_word: 'thoroughly'
  56:
    word: 'błogosławieństwo dla mnie'
    translated_word: 'blessing to me'
  57:
    word: 'klej'
    translated_word: 'glue'
  58:
    word: 'bałagan'
    translated_word: 'mess'
  59:
    word: 'przekonać'
    translated_word: 'convince'
  60:
    word: 'sędzia'
    translated_word: 'judge'
  61:
    word: 'nadąć'
    translated_word: 'bloat'
  62:
    word: 'rzadko'
    translated_word: 'rarely'
  63:
    word: 'kłócić się'
    translated_word: 'argue'
  64:
    word: 'ujednolicić'
    translated_word: 'unify'
  65:
    word: 'w odniesieniu do'
    translated_word: 'regarding to'
  66:
    word: 'podzielony'
    translated_word: 'devided'
  67:
    word: 'jak na razie'
    translated_word: 'as for now'
  68:
    word: 'odtworzone'
    translated_word: 'recreated'
  69:
    word: 'wśród czegoś'
    translated_word: 'among to something'
  70:
    word: 'oprócz'
    translated_word: 'apart from'
  71:
    word: 'na szczęście'
    translated_word: 'fortunately'
  72:
    word: 'ułatwiać'
    translated_word: 'facilitate'
  73:
    word: 'rzucanie'
    translated_word: 'throwing'
  74:
    word: 'niezwykły'
    translated_word: 'unusual'
  75:
    word: 'Standard przemysłowy'
    translated_word: 'industry standard'
  76:
    word: 'przeznaczone do pracy'
    translated_word: 'intended to work'
  77:
    word: 'jak zamierzono'
    translated_word: 'as intended'
  78:
    word: 'przypuszczać'
    translated_word: 'suppose'
  79:
    word: 'niezależny'
    translated_word: 'independent'
  80:
    word: 'trochę'
    translated_word: 'kinda'
  81:
    word: 'zadowolony'
    translated_word: 'glad'
  82:
    word: 'rektyfikowane'
    translated_word: 'rectified'
  83:
    word: 'pod względem ogromnych problemów'
    translated_word: 'in terms of huge problems'
  84:
    word: 'doceniać'
    translated_word: 'appreciate'
  85:
    word: 'poprawki'
    translated_word: 'tweaks'
  86:
    word: 'przyzwoity kształt'
    translated_word: 'decent shape'
  87:
    word: 'właściwy'
    translated_word: 'appropriate'
  88:
    word: 'w prosty sposób'
    translated_word: 'in plain'
  89:
    word: 'ekspansja'
    translated_word: 'expansion'
  90:
    word: 'złożoność'
    translated_word: 'complexity'
  91:
    word: 'ujawnił'
    translated_word: 'revealed'
  92:
    word: 'Sprawa'
    translated_word: 'Concern'
  93:
    word: 'osada'
    translated_word: 'settlement'
  94:
    word: 'komisja'
    translated_word: 'commission'
  95:
    word: 'przeznaczyć'
    translated_word: 'allocate'
  96:
    word: 'natychmiast'
    translated_word: 'immediately'
  97:
    word: 'trzymać'
    translated_word: 'hold'
  98:
    word: 'trzymać'
    translated_word: 'keep'
  99:
    word: 'konkurent'
    translated_word: 'competitor'
  100:
    word: 'podstawa'
    translated_word: 'basis'
  101:
    word: 'licencjodawca'
    translated_word: 'licensor'
  102:
    word: 'właściciel'
    translated_word: 'licensee'
  103:
    word: 'dotacja'
    translated_word: 'grant'
  104:
    word: 'oddziaływać'
    translated_word: 'affect'
  105:
    word: 'na czym nam zależy'
    translated_word: 'do we care about'
  106:
    word: 'księga główna'
    translated_word: 'ledger'
  107:
    word: 'odebrany'
    translated_word: 'picked up'
  108:
    word: 'akumulacja'
    translated_word: 'accumulation'
  109:
    word: 'wyjaśniać'
    translated_word: 'clarify'
  110:
    word: 'rozstrzygać'
    translated_word: 'settle'
  111:
    word: 'pozbyć się tego'
    translated_word: 'rid of it'
  112:
    word: 'idź naprzód'
    translated_word: 'go forward'
  113:
    word: 'udzielanie dostępu'
    translated_word: 'granting access'
  114:
    word: 'okazać się'
    translated_word: 'turn out'
  115:
    word: 'dokładny'
    translated_word: 'exact'
  116:
    word: 'Cały'
    translated_word: 'entire'
  117:
    word: 'złagodzić'
    translated_word: 'mitigate'
  118:
    word: 'opłata'
    translated_word: 'charge'
  119:
    word: 'zachowywać się'
    translated_word: 'behave'
  120:
    word: 'natychmiast'
    translated_word: 'immediately'
  121:
    word: 'wymawiać'
    translated_word: 'pronounce'
  122:
    word: 'przytłoczony'
    translated_word: 'overwhelmed'
  123:
    word: 'przewaga'
    translated_word: 'leverage'
  124:
    word: 'pogodzić'
    translated_word: 'reconcicle'
  125:
    word: 'prostokąt'
    translated_word: 'rectangle'
  126:
    word: 'narzuta'
    translated_word: 'overlay'
  127:
    word: 'kluczowa część'
    translated_word: 'crucial part'
  128:
    word: 'przewidywać'
    translated_word: 'foresee'
  129:
    word: 'samo'
    translated_word: 'itself'
  130:
    word: 'spożytkować'
    translated_word: 'utilize'
  131:
    word: 'powód'
    translated_word: 'reason'
  132:
    word: 'rozsądny'
    translated_word: 'reasonable'
  133:
    word: 'po prostu'
    translated_word: 'simply'
  134:
    word: 'oprócz'
    translated_word: 'beside'
  135:
    word: 'chociaż'
    translated_word: 'though'
136:
  word: 'jeżeli chodzi o'
  translated_word: 'regarding to'
137:
  word: 'wkurzać'
  translated_word: 'pissing off'
138:
  word: 'rozwiązać'
  translated_word: 'figure it out'
139:
  word: 'oddzielny'
  translated_word: 'discrete'
140:
  word: 'zdenerwowany'
  translated_word: 'upset'
141:
  word: 'pod względem'
  translated_word: 'in terms of'
142:
  word: 'wąski'
  translated_word: 'narrow'
143:
  word: 'zaniepokojony'
  translated_word: 'concerned'
144:
  word: 'trochę dziwne'
  translated_word: 'quite strange'
145:
  word: 'przestrzeń do oddychania'
  translated_word: 'breathing space'
146:
  word: 'ewoluował'
  translated_word: 'evolved'
147:
  word: 'inspiruje'
  translated_word: 'inspires'
148:
  word: 'być może'
  translated_word: 'perhaps'
149:
  word: 'pozbyć się'
  translated_word: 'get rid of'
150:
  word: 'dosyć szybko'
  translated_word: 'quite fast'
151:
  word: 'doceniać'
  translated_word: 'appreciate'
152:
  word: 'rozbieżności'
  translated_word: 'discrepancies'
153:
  word: 'gładki'
  translated_word: 'smooth'
